title: "US Power Outages and Economic Strength"
description: "An analysis of outage severity, economic indicators, and structural vulnerabilities (2000â€“2016)."
theme: jekyll-theme-cayman

# Build settings
markdown: kramdown
highlighter: rouge

# Navigation (auto-shows on some themes)
collections:
  pages:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag


